[package]
name = "partition_numbers"
version = "0.1.0"
edition = "2021"

[lib]
name = "partition_numbers"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
